### ISSUE TITLE
can this work with PF_RING?

### ISSUE THREAD

**Issue by hackrole** [caoqianli/httpcap#22]
I like this tools. but we need it to have a good performance. I usualy use PF_RING to speed up the lipcap. So I would to know if this can work with PF_RING?

**Comment by caoqianli** [comment]
I don't know much about PF_RING, but i'm afraid httpcap could not use it

**Comment by hackrole** [comment]
I saw it. I would have a try on it and as I finish it. I would give a reply back here.
