### ISSUE TITLE
why the python version does not support live capture?

### ISSUE THREAD

**Issue by hackrole** [caoqianli/httpcap#23]
I would to rewrite this library to capture data and save them into redis. But the python version seems not support live capture. I am not good at the golang. So I would like to know if it is difficult to make the python-version support live capture.

**Comment by caoqianli** [comment]
It should not difficult to support live capture, just capture tcp packets from network device instead of reading from pcap file.however, the current python version may leaks if tcp fin packets are lost.

**Comment by hackrole** [comment]
I got it.
